"""add processing_error to emails

Revision ID: af5513c9e943
Revises: 26e2e9df97d8
Create Date: 2026-02-26 17:12:29.233150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af5513c9e943'
down_revision: Union[str, None] = '26e2e9df97d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('processing_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'processing_error')
    # ### end Alembic commands ###
